export interface PaymentReceiptData {
  readonly recipientName: string;
  readonly amount: number; // in cents
  readonly paymentDate: string;
  readonly paymentMethod: string; // e.g. "Visa ending in 4242"
  readonly description: string;
  readonly transactionId: string;
  readonly businessName: string;
}

export function generatePaymentReceiptHtml(data: PaymentReceiptData): string {
  const formattedAmount = (data.amount / 100).toFixed(2);

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Payment Receipt</title>
</head>
<body style="margin: 0; padding: 0; background-color: #f3f4f6; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color: #f3f4f6; padding: 40px 0;">
    <tr>
      <td align="center">
        <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
          <!-- Header -->
          <tr>
            <td style="background-color: #0f172a; padding: 32px; text-align: center;">
              <h1 style="margin: 0; color: #ffffff; font-size: 24px; font-weight: 700;">KleanHQ</h1>
              <p style="margin: 8px 0 0; color: #94a3b8; font-size: 14px;">Payment Confirmation</p>
            </td>
          </tr>

          <!-- Success Icon -->
          <tr>
            <td style="padding: 32px 32px 0; text-align: center;">
              <div style="display: inline-block; background-color: #dcfce7; border-radius: 50%; width: 64px; height: 64px; line-height: 64px; font-size: 32px;">
                &#10003;
              </div>
            </td>
          </tr>

          <!-- Body -->
          <tr>
            <td style="padding: 24px 32px 32px;">
              <h2 style="margin: 0 0 8px; color: #16a34a; font-size: 20px; font-weight: 700; text-align: center;">
                Payment Successful
              </h2>
              <p style="margin: 0 0 24px; color: #6b7280; font-size: 14px; text-align: center;">
                Hi ${escapeHtml(data.recipientName)}, your payment has been processed successfully.
              </p>

              <!-- Receipt Details -->
              <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color: #f8fafc; border-radius: 8px; margin-bottom: 24px;">
                <tr>
                  <td style="padding: 20px;">
                    <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
                      <tr>
                        <td style="color: #6b7280; font-size: 13px; padding-bottom: 12px;">Amount Paid</td>
                        <td style="color: #0f172a; font-size: 20px; font-weight: 700; text-align: right; padding-bottom: 12px;">$${formattedAmount}</td>
                      </tr>
                      <tr>
                        <td style="color: #6b7280; font-size: 13px; padding-bottom: 8px; border-top: 1px solid #e5e7eb; padding-top: 12px;">Date</td>
                        <td style="color: #374151; font-size: 13px; text-align: right; padding-bottom: 8px; border-top: 1px solid #e5e7eb; padding-top: 12px;">${escapeHtml(data.paymentDate)}</td>
                      </tr>
                      <tr>
                        <td style="color: #6b7280; font-size: 13px; padding-bottom: 8px;">Payment Method</td>
                        <td style="color: #374151; font-size: 13px; text-align: right; padding-bottom: 8px;">${escapeHtml(data.paymentMethod)}</td>
                      </tr>
                      <tr>
                        <td style="color: #6b7280; font-size: 13px; padding-bottom: 8px;">Description</td>
                        <td style="color: #374151; font-size: 13px; text-align: right; padding-bottom: 8px;">${escapeHtml(data.description)}</td>
                      </tr>
                      <tr>
                        <td style="color: #6b7280; font-size: 13px;">Transaction ID</td>
                        <td style="color: #374151; font-size: 13px; text-align: right; font-family: monospace;">${escapeHtml(data.transactionId)}</td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>

              <p style="margin: 0; color: #9ca3af; font-size: 12px; text-align: center;">
                This receipt was generated by KleanHQ on behalf of ${escapeHtml(data.businessName)}.
                If you have questions about this charge, please contact ${escapeHtml(data.businessName)} directly.
              </p>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding: 24px 32px; background-color: #f8fafc; border-top: 1px solid #e5e7eb; text-align: center;">
              <p style="margin: 0; color: #9ca3af; font-size: 12px;">
                Powered by KleanHQ
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}

function escapeHtml(text: string): string {
  const map: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;',
  };
  return text.replace(/[&<>"']/g, (char) => map[char] ?? char);
}
